// Reads src/posts/*.md → renders markdown, generates branded cover images, and
// writes a typed module (src/content/posts.generated.ts) consumed by both the
// client bundle and the SSR/prerender step. Single source of truth for blog data.

import { readFileSync, writeFileSync, mkdirSync, readdirSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import matter from 'gray-matter'
import { marked } from 'marked'
import sharp from 'sharp'

const __dirname = dirname(fileURLToPath(import.meta.url))
const root = join(__dirname, '..')
const postsDir = join(root, 'src', 'posts')
const outFile = join(root, 'src', 'content', 'posts.generated.ts')
const coversDir = join(root, 'public', 'assets', 'blog')

const SITE = 'https://www.fiscalpoint.com.do'

// Gradient end-color per category (falls back to brand accent).
const CATEGORY_COLOR = {
  'Facturación electrónica': '#2a6fdb',
  DGII: '#1f8a5b',
  Guías: '#7c4dd6',
}

function slugify(str) {
  return String(str)
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
}

function toISODate(value) {
  if (value instanceof Date) return value.toISOString().slice(0, 10)
  return String(value).slice(0, 10)
}

function escapeXml(s) {
  return String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

function wrapText(text, max) {
  const words = text.split(/\s+/)
  const lines = []
  let line = ''
  for (const w of words) {
    if ((line + ' ' + w).trim().length > max && line) {
      lines.push(line.trim())
      line = w
    } else {
      line = (line + ' ' + w).trim()
    }
  }
  if (line) lines.push(line.trim())
  return lines.slice(0, 4)
}

async function makeCover(post) {
  const end = CATEGORY_COLOR[post.category] || '#2a6fdb'
  const lines = wrapText(post.title, 26)
  const startY = 300 - (lines.length - 1) * 37
  const tspans = lines
    .map((l, i) => `<tspan x="80" dy="${i === 0 ? 0 : 74}">${escapeXml(l)}</tspan>`)
    .join('')

  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="630">
    <defs>
      <linearGradient id="g" x1="0" y1="0" x2="1" y2="1">
        <stop offset="0" stop-color="#101a33"/>
        <stop offset="1" stop-color="${end}"/>
      </linearGradient>
    </defs>
    <rect width="1200" height="630" fill="url(#g)"/>
    <circle cx="1060" cy="120" r="280" fill="#ffffff" opacity="0.05"/>
    <circle cx="120" cy="600" r="180" fill="#ffffff" opacity="0.04"/>
    <text x="80" y="108" font-family="Arial, Helvetica, sans-serif" font-size="26" font-weight="700" letter-spacing="4" fill="#9fc0f5">FISCALPOINT · BLOG</text>
    <text x="80" y="165" font-family="Arial, Helvetica, sans-serif" font-size="24" font-weight="700" letter-spacing="1" fill="#ffffff" opacity="0.72">${escapeXml(post.category.toUpperCase())}</text>
    <text x="80" y="${startY}" font-family="Arial, Helvetica, sans-serif" font-size="62" font-weight="800" fill="#ffffff">${tspans}</text>
    <text x="80" y="565" font-family="Arial, Helvetica, sans-serif" font-size="26" font-weight="600" fill="#cfe0fb">fiscalpoint.com.do/blog</text>
  </svg>`

  const buf = Buffer.from(svg)
  mkdirSync(coversDir, { recursive: true })
  await sharp(buf).webp({ quality: 82 }).toFile(join(coversDir, `${post.slug}.webp`))
  await sharp(buf).png({ compressionLevel: 9 }).toFile(join(coversDir, `${post.slug}.png`))
}

async function run() {
  const files = readdirSync(postsDir).filter((f) => f.endsWith('.md'))
  const posts = []

  for (const file of files) {
    const raw = readFileSync(join(postsDir, file), 'utf-8')
    const { data, content } = matter(raw)
    const slug = data.slug || file.replace(/\.md$/, '')
    const words = content.trim().split(/\s+/).length
    const readingTime = `${Math.max(1, Math.round(words / 200))} min`
    const html = marked.parse(content, { async: false })

    const post = {
      slug,
      title: data.title,
      description: data.description,
      date: toISODate(data.date),
      updated: toISODate(data.updated || data.date),
      author: data.author || 'Equipo FiscalPoint',
      category: data.category || 'General',
      categorySlug: slugify(data.category || 'General'),
      tags: Array.isArray(data.tags) ? data.tags : [],
      cover: data.cover || `/assets/blog/${slug}.webp`,
      coverAlt: data.coverAlt || data.title,
      canonical: data.canonical || `${SITE}/blog/${slug}`,
      readingTime: data.readingTime || readingTime,
      draft: Boolean(data.draft),
      html,
    }

    posts.push(post)
    if (!post.draft) await makeCover(post)
  }

  // Newest first
  posts.sort((a, b) => (a.date < b.date ? 1 : -1))

  const banner =
    '// AUTO-GENERATED by scripts/build-posts.mjs — do not edit by hand.\n' +
    '// Edit posts in src/posts/*.md and re-run `npm run posts`.\n'
  const types = `export interface GeneratedPost {
  slug: string
  title: string
  description: string
  date: string
  updated: string
  author: string
  category: string
  categorySlug: string
  tags: string[]
  cover: string
  coverAlt: string
  canonical: string
  readingTime: string
  draft: boolean
  html: string
}\n\n`
  const body = `export const POSTS: GeneratedPost[] = ${JSON.stringify(posts, null, 2)}\n`

  mkdirSync(dirname(outFile), { recursive: true })
  writeFileSync(outFile, banner + '\n' + types + body)
  console.log(`✓ built ${posts.length} post(s) → src/content/posts.generated.ts`)
}

run().catch((err) => {
  console.error('build-posts failed:', err)
  process.exit(1)
})
